//
//  SupplementaryInfoInteractor.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SupplementaryInfoInteractor: SupplementaryInfoInteractorInputProtocol {
    func updateLoginSocial(socialParam: UpdateProfileSocial) {
        ProgressView.shared.show()
        
        Provider.shared.userAPIService.updateProfileSocial(param: socialParam, success: { user in
            ProgressView.shared.hide()
            self.presenter?.didLogin(user: user)
        }) { error in
            ProgressView.shared.hide()
            self.presenter?.didLogin(error: error)
        }
        
    }
    
    weak var presenter: SupplementaryInfoInteractorOutputProtocol?
}
