//
//  SupplementaryInfoRouter.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SupplementaryInfoRouter: SupplementaryInfoWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> SupplementaryInfoViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SupplementaryInfoViewController.initFromNib()
        let interactor = SupplementaryInfoInteractor()
        let router = SupplementaryInfoRouter()
        let presenter = SupplementaryInfoPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showPolicy() {
        let vc =  WebViewController.initFromNib()
        vc.isPush = false
        let nv = UINavigationController(rootViewController: vc)
        self.viewController?.present(controller: nv, animated: true)
    }
}
