//
//  NotificationInteractor.swift
//  RedStar
//
//  Created Ngoc Duong on 12/13/18.
//  Copyright © 2018 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationInteractor: NotificationInteractorInputProtocol {

    weak var presenter: NotificationInteractorOutputProtocol?
    
    func getNotification(offset: Int) {
        if offset == 0 {
            ProgressView.shared.show()
        }
        Provider.shared.notificationAPIService.getNotification(offset: offset, success: { notifications in
            ProgressView.shared.hide()
            self.presenter?.didGetNotification(notifications: notifications)
        }) {  error in
            ProgressView.shared.hide()
            self.presenter?.didGetError(error: error)
        }
    }
}
