//
//  NotificationProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NotificationWireframeProtocol: class {

}
//MARK: Presenter -
protocol NotificationPresenterProtocol: class {

    var interactor: NotificationInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol NotificationInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol NotificationInteractorInputProtocol: class {

    var presenter: NotificationInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol NotificationViewProtocol: class {

    var presenter: NotificationPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
