//
//  SupplementaryInfoProtocols.swift
//  Oganban
//
//  Created Admin on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SupplementaryInfoWireframeProtocol: class {

}
//MARK: Presenter -
protocol SupplementaryInfoPresenterProtocol: class {

    var interactor: SupplementaryInfoInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SupplementaryInfoInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SupplementaryInfoInteractorInputProtocol: class {

    var presenter: SupplementaryInfoInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SupplementaryInfoViewProtocol: class {

    var presenter: SupplementaryInfoPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
