//
//  MyBuyViewController.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import DropDown

class MyBuyViewController: BaseViewController {

    @IBOutlet weak var tbMyBuy: UITableView!
    @IBOutlet weak var vRecordBuy: UIView!
    @IBOutlet weak var lbStatusRecord: UILabel!
    @IBOutlet weak var lbTotal: UILabel!
    @IBOutlet weak var vDropDownStatus: UIView!
    
	var presenter: MyBuyPresenterProtocol?

    let dropDownStatus = DropDown()
    
    var dataOrder: BaseOrderEntity? {
        didSet {
            tbMyBuy.reloadData()
            
            if let count = self.dataOrder?.dataOrder.count {
                if count == 0 {
                    tbMyBuy.isHidden = true
                    showNoData()
                } else {
                    tbMyBuy.isHidden = false
                    hideNoData()
                    setupDropDownStatus()
                }
            }
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

    func setupView() {
        self.setTitleNavigation(title: NavigationTitle.myBuy)
        configTableView()
        setupDropDownStatus()
        getData()
        guard let countOrder = self.dataOrder?.dataOrder.count else { return }
        self.lbTotal.text = "Tổng đơn hàng đang chờ duyệt: \(countOrder)"
        
    }
    
    func getData() {
        presenter?.getHistoryOrder(status: "new", offset: 0, limit: 10)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        showTabbar()
    }
    
    func configTableView() {
        tbMyBuy.dataSource = self
        tbMyBuy.delegate = self
        
        tbMyBuy.registerTableCell(MyBuyCell.self)
        
        tbMyBuy.contentInset.bottom = 10
    }
    
    private func setupDropDownStatus() {
        dropDownStatus.anchorView = vDropDownStatus
        dropDownStatus.backgroundColor = AppColor.main
        DropDown.appearance().setupCornerRadius(10)
        dropDownStatus.textColor = .white
        dropDownStatus.textFont = AppFont.fontRegular11
        dropDownStatus.separatorColor = .gray
        dropDownStatus.selectionBackgroundColor = AppColor.main
        dropDownStatus.selectedTextColor = .yellow
        dropDownStatus.downScaleTransform = CGAffineTransform(rotationAngle: (-.pi))
        dropDownStatus.dataSource = ["Chờ duyệt", "Đang giao", "Hoàn Tất", "Đã huỷ", "Tất cả"]
        dropDownStatus.selectionAction = { [weak self](index, item) in
            guard let `self` = self else { return }
            self.lbStatusRecord.text = item
            
            switch item {
            case "Chờ duyệt":
                self.presenter?.getHistoryOrder(status: StatusType.new.rawValue, offset: 0, limit: 10)
                if let countOrder = self.dataOrder?.dataOrder.count {
                    if countOrder > 0 {
                        self.lbTotal.text = "Tổng đơn hàng đang chờ duyệt: \(countOrder)"
                    } else {
                        self.lbTotal.text = "Tổng đơn hàng đang chờ duyệt: 0"
                    }
                }
                
            case "Đang giao":
                self.presenter?.getHistoryOrder(status: StatusType.wait_delivery.rawValue, offset: 0, limit: 10)
                if let countOrder = self.dataOrder?.dataOrder.count {
                    if countOrder > 0 {
                        self.lbTotal.text = "Tổng đơn hàng đang giao: \(countOrder)"
                    } else {
                        self.lbTotal.text = "Tổng đơn hàng đang giao: 0"
                    }
                }
            case "Hoàn Tất":
                self.presenter?.getHistoryOrder(status: StatusType.done.rawValue, offset: 0, limit: 10)
                if let countOrder = self.dataOrder?.dataOrder.count {
                    if countOrder > 0 {
                        self.lbTotal.text = "Tổng đơn hàng đã hoàn tất: \(countOrder)"
                    } else {
                        self.lbTotal.text = "Tổng đơn hàng đã hoàn tất: 0"
                    }
                }
            case "Đã huỷ":
                self.presenter?.getHistoryOrder(status: StatusType.cancel.rawValue, offset: 0, limit: 10)
                if let countOrder = self.dataOrder?.dataOrder.count {
                    if countOrder > 0 {
                        self.lbTotal.text = "Tổng đơn hàng đã huỷ: \(countOrder)"
                    } else {
                        self.lbTotal.text = "Tổng đơn hàng đã huỷ: 0"
                    }
                }
            case "Tất cả":
                self.presenter?.getHistoryOrder(status: StatusType.all.rawValue, offset: 0, limit: 10)
                if let countOrder = self.dataOrder?.dataOrder.count {
                    if countOrder > 0 {
                        self.lbTotal.text = "Tổng tất cả các đơn hàng: \(countOrder)"
                    } else {
                        self.lbTotal.text = "Tổng tất cả các đơn hàng: 0"
                    }
                }
            default:
                break
            }
        }
    }
    
    @IBAction func btnChangeStatusRecord() {
        dropDownStatus.show()
    }
}

extension MyBuyViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let count = dataOrder?.dataOrder.count else { return 0 }
        return count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(MyBuyCell.self)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 140
    }
    
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

        let vc = MyBuyDetailRouter.createModule()
        self.push(controller: vc)
    }
}

extension MyBuyViewController: MyBuyViewProtocol {
    func didGetHistoryOrder(data: BaseOrderEntity?) {
        self.dataOrder = data
    }
}
