//
//  MorePresenter.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MorePresenter: MorePresenterProtocol {
   
    weak private var view: MoreViewProtocol?
    var interactor: MoreInteractorInputProtocol?
    private let router: MoreWireframeProtocol

    init(interface: MoreViewProtocol, interactor: MoreInteractorInputProtocol?, router: MoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func goToPage(name: MoreEntityType) {
        if name == .logout {
            PopUpHelper.shared.showYesNoQuestionHaveAds(question: "Bạn chắc chắn muốn đăng xuất?", completionYes: {
                self.logout()
            }) {
                //----
            }
            
        } else {
            router.goToPage(name: name)
        }
    }

    func logout() {
        interactor?.logout()
    }
    
    func getProfileUser() {
        interactor?.getProfileUser()
    }
}

extension MorePresenter: MoreInteractorOutputProtocol {
    func logoutSuccess() {
        view?.logoutSuccess()
    }
    
    func didGetProfileUser(user: UserEntity?) {
        view?.didGetProfileUser(user: user)
    }
}
