//
//  MoreProtocols.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MoreWireframeProtocol: class {
    func goToPage(name: MoreEntityType)

}
//MARK: Presenter -
protocol MorePresenterProtocol: class {

    var interactor: MoreInteractorInputProtocol? { get set }
    func goToPage(name: MoreEntityType)
    func logout()
    func getProfileUser()
}

//MARK: Interactor -
protocol MoreInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func logoutSuccess()
    func didGetProfileUser(user: UserEntity?)
}

protocol MoreInteractorInputProtocol: class {

    var presenter: MoreInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func logout()
    func getProfileUser()
}

//MARK: View -
protocol MoreViewProtocol: class {

    var presenter: MorePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func logoutSuccess()
    func didGetProfileUser(user: UserEntity?)
}
