//
//  HistoryBuyProtocols.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryBuyWireframeProtocol: class {
    func gotoLogin()
}
//MARK: Presenter -
protocol HistoryBuyPresenterProtocol: class {

    var interactor: HistoryBuyInteractorInputProtocol? { get set }
    func getHistoryBuy(offset: Int)
    func gotoLogin()
}

//MARK: Interactor -
protocol HistoryBuyInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getSucessHistoryBuy(history: [HistoryBuyEntity])
    func getErrorHistoryBuy(error: APIError?)
}

protocol HistoryBuyInteractorInputProtocol: class {

    var presenter: HistoryBuyInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getHistoryBuy(offset: Int)
}

//MARK: View -
protocol HistoryBuyViewProtocol: class {

    var presenter: HistoryBuyPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getSucessHistoryBuy(history: [HistoryBuyEntity])
    func getErrorHistoryBuy(error: APIError?)
}
