//
//  HistoryBuyViewController.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryBuyViewController: BaseViewController {

    var presenter: HistoryBuyPresenterProtocol?
    @IBOutlet weak var tvHistory: UITableView!
    
    var refreshControl:  UIRefreshControl!
    var canLoadMore = false
    var isRefresh = false
    
    var historyList = [HistoryBuyEntity]() {
        didSet {
            tvHistory.reloadData()
            if self.historyList.isEmpty {
                tvHistory.isHidden = true
                showNoData()
            } else {
                hideNoData()
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.addBackToNavigation(icon: AppImage.imgWhiteBack)
        self.setTitleNavigation(title: NavigationTitle.historyBuy)
        configureTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        hideTabbar()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        pullToRefresh()
    }
    
    func configureTableView() {
        tvHistory.dataSource = self
        tvHistory.delegate = self
        tvHistory.registerXibFile(HistoryBuyCell.self)
        tvHistory.tableFooterView = UIView()
        tvHistory.estimatedRowHeight = 100
        tvHistory.translatesAutoresizingMaskIntoConstraints = false
        tvHistory.rowHeight = UITableView.automaticDimension
        refreshControl = UIRefreshControl()
        refreshControl.addTarget(self, action: #selector(pullToRefresh), for: .valueChanged)
        tvHistory.addSubview(refreshControl)
    }
    
    @objc func pullToRefresh() {
        isRefresh = true
        self.refreshControl.endRefreshing()
        presenter?.getHistoryBuy(offset: 0)
    }
}
extension HistoryBuyViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return historyList.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(HistoryBuyCell.self, for: indexPath) as HistoryBuyCell
        cell.showData(history: historyList[indexPath.row])
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return  UITableView.automaticDimension
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if canLoadMore && indexPath.item == self.historyList.count - 5 {
            presenter?.getHistoryBuy(offset: self.historyList.count)
        }
    }
}

extension HistoryBuyViewController: HistoryBuyViewProtocol{
    func getSucessHistoryBuy(history: [HistoryBuyEntity]) {
        canLoadMore = false
        //guard let _history = history else { return }
        canLoadMore = history.count == limitLoad
        
        if self.historyList.isEmpty || isRefresh {
            isRefresh = false
            self.historyList = history
        } else {
            self.historyList.append(contentsOf: history)
        }
    }
    
    func getErrorHistoryBuy(error: APIError?) {
        canLoadMore = false
        self.historyList = []
    }
}
