//
//  HistoryBuyInteractor.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryBuyInteractor: HistoryBuyInteractorInputProtocol {
    
    weak var presenter: HistoryBuyInteractorOutputProtocol?
    
    func getHistoryBuy(offset: Int) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.getHistoryBuy(offset: offset, success: { (histories) in
            ProgressView.shared.hide()
            self.presenter?.getSucessHistoryBuy(history: histories)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.getErrorHistoryBuy(error: error)
        }
    }
}

