//
//  MySellExpiredProtocols.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MySellExpiredWireframeProtocol: class {

}
//MARK: Presenter -
protocol MySellExpiredPresenterProtocol: class {

    var interactor: MySellExpiredInteractorInputProtocol? { get set }
    
    func getSellExpired(status: String, limit: Int, offset: Int)
}

//MARK: Interactor -
protocol MySellExpiredInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetSellPired(data: BaseRecordEntity?)
    func didGetSellPired(error: APIError?)
}

protocol MySellExpiredInteractorInputProtocol: class {

    var presenter: MySellExpiredInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getSellExpired(status: String, limit: Int, offset: Int)
}

//MARK: View -
protocol MySellExpiredViewProtocol: class {

    var presenter: MySellExpiredPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetSellPired(data: BaseRecordEntity?)
    func didGetSellPired(error: APIError?)
}
