//
//  MySellExpiredInteractor.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellExpiredInteractor: MySellExpiredInteractorInputProtocol {

    weak var presenter: MySellExpiredInteractorOutputProtocol?
    
    func getSellExpired(status: String, limit: Int, offset: Int) {
        Provider.shared.recordAPIService.getRecordSellerPost(status: status, offset: offset, limit: limit, success: { (data) in
            self.presenter?.didGetSellPired(data: data)
        }) { (_) in
            
        }
    }
}
