//
//  SettingProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SettingWireframeProtocol: class {

}
//MARK: Presenter -
protocol SettingPresenterProtocol: class {

    var interactor: SettingInteractorInputProtocol? { get set }
    func getPositionRange()
}

//MARK: Interactor -
protocol SettingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetPositionRange(list: [PositionRangeEntity])
}

protocol SettingInteractorInputProtocol: class {

    var presenter: SettingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getPositionRange()
}

//MARK: View -
protocol SettingViewProtocol: class {

    var presenter: SettingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetPositionRange(list: [PositionRangeEntity])
}
