//
//  HistoryCoinProtocols.swift
//  Oganban
//
//  Created Admin on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryCoinWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryCoinPresenterProtocol: class {

    var interactor: HistoryCoinInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol HistoryCoinInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HistoryCoinInteractorInputProtocol: class {

    var presenter: HistoryCoinInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryCoinViewProtocol: class {

    var presenter: HistoryCoinPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
