//
//  HistoryCoinInteractor.swift
//  Oganban
//
//  Created Admin on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryCoinInteractor: HistoryCoinInteractorInputProtocol {

    weak var presenter: HistoryCoinInteractorOutputProtocol?
}
