//
//  ChangePasswordPresenter.swift
//  Oganban
//
//  Created Coby on 12/28/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangePasswordPresenter: ChangePasswordPresenterProtocol {

    weak private var view: ChangePasswordViewProtocol?
    var interactor: ChangePasswordInteractorInputProtocol?
    private let router: ChangePasswordWireframeProtocol

    init(interface: ChangePasswordViewProtocol, interactor: ChangePasswordInteractorInputProtocol?, router: ChangePasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func changePassword(password: String, newPassword: String) {
        interactor?.changePassword(password: password, newPassword: newPassword)
    }
}

extension ChangePasswordPresenter: ChangePasswordInteractorOutputProtocol {
    func didChangePassword(data: BaseResponseString?) {
        view?.didChangePassword(data: data)
    }
    
    func didChangePassword(error: APIError?) {
        view?.didChangePassword(error: error)
    }
    
    func didChangePassword(data: BaseResponseString) {
        
    }
}
