//
//  ChangePasswordInteractor.swift
//  Oganban
//
//  Created Coby on 12/28/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangePasswordInteractor: ChangePasswordInteractorInputProtocol {

    weak var presenter: ChangePasswordInteractorOutputProtocol?
    
    func changePassword(password: String, newPassword: String) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.changePassword(current: password, new: newPassword, success: { (data) in
            ProgressView.shared.hide()
            self.presenter?.didChangePassword(data: data)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.didChangePassword(error: error)
        }
    }
}
