//
//  MyBuyDetailPresenter.swift
//  Oganban
//
//  Created Kai Pham on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyBuyDetailPresenter: MyBuyDetailPresenterProtocol, MyBuyDetailInteractorOutputProtocol {
    
    

    weak private var view: MyBuyDetailViewProtocol?
    var interactor: MyBuyDetailInteractorInputProtocol?
    private let router: MyBuyDetailWireframeProtocol

    init(interface: MyBuyDetailViewProtocol, interactor: MyBuyDetailInteractorInputProtocol?, router: MyBuyDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getDetailOrder(id: String) {
        interactor?.getDetailOrder(id: id)
    }
    
    
    func changedStatusOrder(status: OrderStatusKey, id: String) {
        interactor?.changedStatusOrder(status: status, id: id)
    }

    func changedStatusOrderSaler(status: OrderStatusKey, id: String) {
        interactor?.changedStatusOrderSaler(status: status, id: id)
    }
    
    func postRating(point: Int, accountID: String, isBuyer: Bool, orderID: String) {
        interactor?.postRating(point: point, accountID: accountID, isBuyer: isBuyer, orderID: orderID)
    }
    
    //-----
    func didGetOrder(order: OrderDetailEntity?) {
        view?.didGetOrder(order: order)
    }
    
    func didPostRating(data: BaseResponse?) {
        view?.didPostRating(data: data)
    }
}
