//
//  MyBuyDetailInteractor.swift
//  Oganban
//
//  Created Kai Pham on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyBuyDetailInteractor: MyBuyDetailInteractorInputProtocol {

    weak var presenter: MyBuyDetailInteractorOutputProtocol?
    
    func getDetailOrder(id: String) {
        ProgressView.shared.show()
        Provider.shared.orderAPIService.getDetailOrder(id: id, success: { order in
            ProgressView.shared.hide()
            self.presenter?.didGetOrder(order: order)
        }) { error in
            ProgressView.shared.hide()
            PopUpHelper.shared.showMessageHaveAds(error: error)
        }
    }
    
    func changedStatusOrder(status: OrderStatusKey, id: String) {
        ProgressView.shared.show()
        Provider.shared.orderAPIService.changeStatusOrderBuyer(status: status, id: id, success: { _ in
            self.getDetailOrder(id: id)
        }) { error  in
            ProgressView.shared.hide()
            PopUpHelper.shared.showMessageHaveAds(error: error)
        }
    }
    
    func changedStatusOrderSaler(status: OrderStatusKey, id: String) {
        ProgressView.shared.show()
        Provider.shared.orderAPIService.changeStatusOrderSaler(status: status, id: id, success: { _ in
            self.getDetailOrder(id: id)
        }) { error  in
            ProgressView.shared.hide()
            PopUpHelper.shared.showMessageHaveAds(error: error)
        }
    }
    
    func postRating(point: Int, accountID: String, isBuyer: Bool, orderID: String) {
        Provider.shared.userAPIService.postRating(point: point, accountID: accountID, isBuyer: isBuyer, orderID: orderID, success: { (data) in
            self.presenter?.didPostRating(data: data)
        }) { (_) in
            
        }
    }
}
