//
//  MyBuyDetailPresenter.swift
//  Oganban
//
//  Created Kai Pham on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyBuyDetailPresenter: MyBuyDetailPresenterProtocol, MyBuyDetailInteractorOutputProtocol {

    weak private var view: MyBuyDetailViewProtocol?
    var interactor: MyBuyDetailInteractorInputProtocol?
    private let router: MyBuyDetailWireframeProtocol

    init(interface: MyBuyDetailViewProtocol, interactor: MyBuyDetailInteractorInputProtocol?, router: MyBuyDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getDetailOrder(id: String) {
        interactor?.getDetailOrder(id: id)
    }
    
    func didGetOrder(order: OrderEntity?) {
        view?.didGetOrder(order: order)
    }

}
