//
//  MyBuyDetailViewController.swift
//  Oganban
//
//  Created Kai Pham on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum MyBuyType: Int {
    case infoProduct = 0
    case infoSaler
}

class MyBuyDetailViewController: BaseViewController {

	var presenter: MyBuyDetailPresenterProtocol?
    var listHeader = ["Chi tiết", "Thông tin người bán"]
    
    var order: OrderDetailEntity? {
        didSet {
            tbDetail.reloadData()
        }
    }
    
    var orderId: String = ""

     @IBOutlet weak var tbDetail: UITableView!
	override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter?.getDetailOrder(id: orderId)
        configureTable()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: "Chi tiết đơn hàng")
    }

}

extension MyBuyDetailViewController: MyBuyDetailViewProtocol {
    func didGetOrder(order: OrderDetailEntity?) {
        self.order = order
    }
}


// MARK: table
extension MyBuyDetailViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbDetail.delegate = self
        tbDetail.dataSource = self
        tbDetail.registerXibFile(MyBuyImageCell.self)
        tbDetail.registerXibFile(MyBuyInfoUserCell.self)
        
        tbDetail.separatorStyle = .none
        tbDetail.rowHeight = UITableView.automaticDimension
        tbDetail.estimatedRowHeight = 150
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return listHeader.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        switch indexPath.section {
        case OrderDetailInfoType.infoProduct.rawValue:
            let cell = tbDetail.dequeue(MyBuyImageCell.self, for: indexPath)
            cell.order = self.order
            cell.delegate = self
            return cell
        default:
            let cell = tbDetail.dequeue(MyBuyInfoUserCell.self, for: indexPath)
            cell.recordMyBuy = self.order
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    // Header
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let v = UIView()
        let header = HeaderOrderDetail()
        v.addSubview(header)
        header.fillSuperview()
        if section < self.listHeader.count {
            header.lbTitle.text = self.listHeader[section].uppercased()
            v.backgroundColor = AppColor.gray_65_65_65
        }
        
        return v
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        // comment show header only one
        if section >= self.listHeader.count || section == 0 {
            return 0
        }
        return 47.5
    }
}


extension MyBuyDetailViewController: MyBuyImageCellDelegate {
    func btnCancelTapped() {
        PopUpHelper.shared.showYesNoQuestionHaveAds(question: "Bạn chắc chắn muốn huỷ giao dịch", completionYes: {
            self.presenter?.changedStatusOrder(status: OrderStatusKey.cancel, id: self.orderId)
        }) {
            print("No")
        }
    }
}
