//
//  ProductListInteractor.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListInteractor: ProductListInteractorInputProtocol {

    weak var presenter: ProductListInteractorOutputProtocol?
}
