//
//  ProductListPresenter.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListPresenter: ProductListPresenterProtocol, ProductListInteractorOutputProtocol {

    weak private var view: ProductListViewProtocol?
    var interactor: ProductListInteractorInputProtocol?
    private let router: ProductListWireframeProtocol

    init(interface: ProductListViewProtocol, interactor: ProductListInteractorInputProtocol?, router: ProductListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
