//
//  FavouritePresenter.swift
//  Oganban
//
//  Created Admin on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouritePresenter: FavouritePresenterProtocol, FavouriteInteractorOutputProtocol {

    weak private var view: FavouriteViewProtocol?
    var interactor: FavouriteInteractorInputProtocol?
    private let router: FavouriteWireframeProtocol

    init(interface: FavouriteViewProtocol, interactor: FavouriteInteractorInputProtocol?, router: FavouriteWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
