//
//  FavouriteInteractor.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteInteractor: FavouriteInteractorInputProtocol {
    
    weak var presenter: FavouriteInteractorOutputProtocol?
    
    func getFavourite(offset: Int) {
        
        ProgressView.shared.show()
        Provider.shared.userAPIService.getFavourite(offset: offset, success: { (favourites) in
            ProgressView.shared.hide()
             self.presenter?.getSucessFavourite(favourite: favourites)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.getErrorFavourite(error: error)
        }
    }
    
    func addRemoveFavourite(isFavorite: Int, accountId: Int) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.addRemoveFavourite(isFavorite: isFavorite, accountId: accountId, success: { (baseResponse) in
            ProgressView.shared.hide()
            self.presenter?.addRemoveSucessFavourite(baseResponse: baseResponse)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.getErrorFavourite(error: error)
        }
    }
}
