//
//  FavouriteInteractor.swift
//  Oganban
//
//  Created Admin on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteInteractor: FavouriteInteractorInputProtocol {

    weak var presenter: FavouriteInteractorOutputProtocol?
}
