//
//  FavouriteViewController.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteViewController: BaseViewController {
    
    var presenter: FavouritePresenterProtocol?
    
    @IBOutlet weak var tvFavourite: UITableView!
    
    var refreshControl:  UIRefreshControl!
    var canLoadMore = false
    var isRefresh = false
    
    var favouriteList = [FavouriteEntity]() {
        didSet {
            tvFavourite.reloadData()
            if self.favouriteList.isEmpty {
                tvFavourite.isHidden = true
                showNoData()
            } else {
                hideNoData()
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.addBackToNavigation(icon: AppImage.imgWhiteBack)
        self.setTitleNavigation(title: NavigationTitle.favourite)
        configureTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        presenter?.getFavourite(offset: 0)
    }
    
    func configureTableView() {
        tvFavourite.dataSource = self
        tvFavourite.delegate = self
        tvFavourite.registerXibFile(FavouriteCell.self)
        tvFavourite.tableFooterView = UIView()
        refreshControl = UIRefreshControl()
        refreshControl.addTarget(self, action: #selector(pullToRefresh), for: .valueChanged)
        tvFavourite.addSubview(refreshControl)
    }
    
    @objc func pullToRefresh() {
        isRefresh = true
        self.refreshControl.endRefreshing()
        presenter?.getFavourite(offset: 0)
    }
}
extension FavouriteViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return favouriteList.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(FavouriteCell.self, for: indexPath) as FavouriteCell
        cell.showData(index: indexPath.row, favourite: favouriteList[indexPath.row])
        cell.delegate = self
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return  85
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if canLoadMore && indexPath.item == self.favouriteList.count - 5 {
            presenter?.getFavourite(offset: self.favouriteList.count)
        }
    }
}

extension FavouriteViewController: FavouriteViewProtocol{
    func getSucessFavourite(favourite: [FavouriteEntity]) {
        canLoadMore = false
        //guard let _favourite = favourite else { return }
        canLoadMore = favourite.count == limitLoad
        
        if self.favouriteList.isEmpty || isRefresh {
            isRefresh = false
            self.favouriteList = favourite
        } else {
            self.favouriteList.append(contentsOf: favourite)
        }
    }
    
    func getErrorFavourite(error: APIError?) {
        canLoadMore = false
        self.favouriteList = []
    }
}

extension FavouriteViewController: FavouriteCellProtocol{
    func removeFavourite(index: Int) {
        self.favouriteList.remove(at: index)
    }
}
