//
//  LoginInteractor.swift
//  Oganban
//
//  Created Kent on 12/19/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GoogleSignIn

class LoginInteractor: LoginInteractorInputProtocol {
    
    weak var presenter: LoginInteractorOutputProtocol?
    
    func login(email: String, password: String) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.login(email: email, password: password, success: { (user) in
            //save user
            ProgressView.shared.hide()
            guard let user = user else { return }
            // --
            self.presenter?.didLogin(user: user)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.didLogin(error: error)
        }
    }
    
    func loginSocial(param: LoginSocialParam) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.loginGmail(param: param, success: { user in
            ProgressView.shared.hide()
            guard let user = user else { return }
            self.presenter?.didLogin(user: user)
        }) { error in
            ProgressView.shared.hide()
            self.presenter?.didLogin(error: error)
        }
    }
    
    func updateProfile(codeVerify: String, phoneCode: String, phoneNumber: String) {
        Provider.shared.userAPIService.verifyPhone(code: codeVerify, phone: phoneNumber, phonCode: phoneCode, success: { (user) in
            self.presenter?.didLogin(user: user)
        }) { (error) in
            self.presenter?.didLogin(error: error)
        }
    }
}
