//
//  NotificationDetailViewController.swift
//  Oganban
//
//  Created Kai Pham on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationDetailViewController: BaseViewController, NotificationDetailViewProtocol {

	var presenter: NotificationDetailPresenterProtocol?
    
    @IBOutlet weak var lbTime: UILabel!
    @IBOutlet weak var lbContent: UILabel!
    
    var notificationEntity: NotificationEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
        showData(notificationEntity: notificationEntity)
    }
    
    func showData(notificationEntity: NotificationEntity?) {
        guard let noti = notificationEntity else { return }
        lbTime.text = noti.createTime?.toString(dateFormat: AppDateFormat.ddMMMyyyySpacehhmma)
        
        lbContent.text = noti.content?.trim()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
    }

}
