//
//  MySellingPresenter.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellingPresenter: MySellingPresenterProtocol {

    weak private var view: MySellingViewProtocol?
    var interactor: MySellingInteractorInputProtocol?
    private let router: MySellingWireframeProtocol

    init(interface: MySellingViewProtocol, interactor: MySellingInteractorInputProtocol?, router: MySellingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getRecordSellerPost(status: String, offset: Int, limit: Int) {
        interactor?.getRecordSellerPost(status: status, offset: offset, limit: limit)
    }
    
}

extension MySellingPresenter: MySellingInteractorOutputProtocol {
    func didGetRecordSellerPost(listRecord: [RecordEntity]) {
        view?.didGetRecordSellerPost(listRecord: listRecord)
    }
    
    func didGetRecordSellerPost(error: APIError?) {
        view?.didGetRecordSellerPost(error: error)
    }
}
