//
//  MySellingRouter.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellingRouter: MySellingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(delegate: MySellingViewControllerDelegate) -> MySellingViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MySellingViewController.initFromNib()
        let interactor = MySellingInteractor()
        let router = MySellingRouter()
        let presenter = MySellingPresenter(interface: view, interactor: interactor, router: router)
        
        view.delegate = delegate
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoMySellExpired() {
        
    }
}
