//
//  MySellingPresenter.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellingPresenter: MySellingPresenterProtocol, MySellingInteractorOutputProtocol {

    weak private var view: MySellingViewProtocol?
    var interactor: MySellingInteractorInputProtocol?
    private let router: MySellingWireframeProtocol

    init(interface: MySellingViewProtocol, interactor: MySellingInteractorInputProtocol?, router: MySellingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
