//
//  MySellContainerInteractor.swift
//  Oganban
//
//  Created Kai Pham on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellContainerInteractor: MySellContainerInteractorInputProtocol {

    weak var presenter: MySellContainerInteractorOutputProtocol?
}
