//
//  MySellContainerPresenter.swift
//  Oganban
//
//  Created Kai Pham on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellContainerPresenter: MySellContainerPresenterProtocol, MySellContainerInteractorOutputProtocol {

    weak private var view: MySellContainerViewProtocol?
    var interactor: MySellContainerInteractorInputProtocol?
    private let router: MySellContainerWireframeProtocol

    init(interface: MySellContainerViewProtocol, interactor: MySellContainerInteractorInputProtocol?, router: MySellContainerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func gotoLogin() {
        router.gotoLogin()
    }
    
    func gotoMySellExpired() {
        router.gotoMySellExpired()
    }
    
    func gotoPostRecord() {
        router.gotoPostRecord()
    }
}
