//
//  PositionRouter.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PositionRouter: PositionWireframeProtocol {
    func dismiss() {
        viewController?.dismiss()
    }

    weak var viewController: UIViewController?

    static func createModule(delegate: PositionViewControllerDelegate) -> PositionViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PositionViewController(nibName: nil, bundle: nil)
        let interactor = PositionInteractor()
        let router = PositionRouter()
        let presenter = PositionPresenter(interface: view, interactor: interactor, router: router)
        view.delegate = delegate
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
