//
//  PositionPresenter.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PositionPresenter: PositionPresenterProtocol, PositionInteractorOutputProtocol {
    func dismiss() {
        router.dismiss()
    }

    weak private var view: PositionViewProtocol?
    var interactor: PositionInteractorInputProtocol?
    private let router: PositionWireframeProtocol

    init(interface: PositionViewProtocol, interactor: PositionInteractorInputProtocol?, router: PositionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
