//
//  PositionProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PositionWireframeProtocol: class {
    func dismiss()
}
//MARK: Presenter -
protocol PositionPresenterProtocol: class {
    
    var interactor: PositionInteractorInputProtocol? { get set }
    func dismiss()
    func getCountRecord(long: CGFloat, lat: CGFloat, radius: Int?)
}

//MARK: Interactor -
protocol PositionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetCountRecord(count: Int)
}

protocol PositionInteractorInputProtocol: class {

    var presenter: PositionInteractorOutputProtocol?  { get set }
    func getCountRecord(long: CGFloat, lat: CGFloat, radius: Int?)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol PositionViewProtocol: class {

    var presenter: PositionPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetCountRecord(count: Int)
}
