//
//  PositionInteractor.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PositionInteractor: PositionInteractorInputProtocol {
    func getCountRecord(long: CGFloat, lat: CGFloat, radius: Int) {
        Provider.shared.categoryAPIService.getCountRecordPosition(long: long, lat: lat, radius: radius, success: { (result) in
            guard let data = result?.data, let count = data as? Int else { return }
            self.presenter?.didGetCountRecord(count: count)
        }) { (error) in
            
        }
    }
    

    weak var presenter: PositionInteractorOutputProtocol?
}
