//
//  PositionInteractor.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PositionInteractor: PositionInteractorInputProtocol {

    weak var presenter: PositionInteractorOutputProtocol?
}
