//
//  MyExchangeDetailRouter.swift
//  Oganban
//
//  Created Coby on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyExchangeDetailRouter: MyExchangeDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MyExchangeDetailViewController(nibName: nil, bundle: nil)
        let interactor = MyExchangeDetailInteractor()
        let router = MyExchangeDetailRouter()
        let presenter = MyExchangeDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
