//
//  MyExchangeDetailInteractor.swift
//  Oganban
//
//  Created Coby on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyExchangeDetailInteractor: MyExchangeDetailInteractorInputProtocol {

    weak var presenter: MyExchangeDetailInteractorOutputProtocol?
}
