//
//  MyExchangeDetailPresenter.swift
//  Oganban
//
//  Created Coby on 1/6/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyExchangeDetailPresenter: MyExchangeDetailPresenterProtocol, MyExchangeDetailInteractorOutputProtocol {

    weak private var view: MyExchangeDetailViewProtocol?
    var interactor: MyExchangeDetailInteractorInputProtocol?
    private let router: MyExchangeDetailWireframeProtocol

    init(interface: MyExchangeDetailViewProtocol, interactor: MyExchangeDetailInteractorInputProtocol?, router: MyExchangeDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
