//
//  ProductListInteractor.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteProductListInteractor: FavouriteProductListInteractorInputProtocol {

    weak var presenter: FavouriteProductListInteractorOutputProtocol?
    
    func getFavourite(accountId: Int, offset: Int) {
        ProgressView.shared.show()
        Provider.shared.userAPIService.getRecordByFavoriteUser(accountId: accountId, offset: offset, success: { (record) in
            ProgressView.shared.hide()
            self.presenter?.getSucessFavourite(record: record)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.getErrorFavourite(error: error)
        }
        
    }
}
