//
//  ProductListProtocols.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FavouriteProductListWireframeProtocol: class {

}
//MARK: Presenter -
protocol FavouriteProductListPresenterProtocol: class {

    var interactor: FavouriteProductListInteractorInputProtocol? { get set }
    func getFavourite(accountId: Int, offset: Int)
}

//MARK: Interactor -
protocol FavouriteProductListInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getSucessFavourite(record: [RecordEntity])
    func getErrorFavourite(error: APIError?)
}

protocol FavouriteProductListInteractorInputProtocol: class {

    var presenter: FavouriteProductListInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getFavourite(accountId: Int, offset: Int)
}

//MARK: View -
protocol FavouriteProductListViewProtocol: class {

    var presenter: FavouriteProductListPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getSucessFavourite(record: [RecordEntity])
    func getErrorFavourite(error: APIError?)
}
