//
//  ProductListRouter.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteProductListRouter: FavouriteProductListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> FavouriteProductListViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FavouriteProductListViewController(nibName: nil, bundle: nil)
        let interactor = FavouriteProductListInteractor()
        let router = FavouriteProductListRouter()
        let presenter = FavouriteProductListPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
