//
//  ProductListPresenter.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteProductListPresenter: FavouriteProductListPresenterProtocol {

    weak private var view: FavouriteProductListViewProtocol?
    var interactor: FavouriteProductListInteractorInputProtocol?
    private let router: FavouriteProductListWireframeProtocol

    init(interface: FavouriteProductListViewProtocol, interactor: FavouriteProductListInteractorInputProtocol?, router: FavouriteProductListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getFavourite(accountId: Int, offset: Int) {
        interactor?.getFavourite(accountId: accountId, offset: offset)
    }
}

extension FavouriteProductListPresenter: FavouriteProductListInteractorOutputProtocol{
    func getSucessFavourite(record: [RecordEntity]) {
        view?.getSucessFavourite(record: record)
    }
    
    func getErrorFavourite(error: APIError?) {
        view?.getErrorFavourite(error: error)
    }
}
