//
//  ProductListProtocols.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProductListWireframeProtocol: class {

}
//MARK: Presenter -
protocol ProductListPresenterProtocol: class {

    var interactor: ProductListInteractorInputProtocol? { get set }
    func getFavourite(offset: Int)
}

//MARK: Interactor -
protocol ProductListInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getSucessFavourite(record: [RecordEntity])
    func getErrorFavourite(error: APIError?)
}

protocol ProductListInteractorInputProtocol: class {

    var presenter: ProductListInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getFavourite(offset: Int)
}

//MARK: View -
protocol ProductListViewProtocol: class {

    var presenter: ProductListPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getSucessFavourite(record: [RecordEntity])
    func getErrorFavourite(error: APIError?)
}
