//
//  ProductListPresenter.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListPresenter: ProductListPresenterProtocol {

    weak private var view: ProductListViewProtocol?
    var interactor: ProductListInteractorInputProtocol?
    private let router: ProductListWireframeProtocol

    init(interface: ProductListViewProtocol, interactor: ProductListInteractorInputProtocol?, router: ProductListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getFavourite(offset: Int) {
        interactor?.getFavourite(offset: offset)
    }
}

extension ProductListPresenter: ProductListInteractorOutputProtocol{
    func getSucessFavourite(record: [RecordEntity]) {
        view?.getSucessFavourite(record: record)
    }
    
    func getErrorFavourite(error: APIError?) {
        view?.getErrorFavourite(error: error)
    }
}
