//
//  ProductListInteractor.swift
//  Oganban
//
//  Created Kent on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListInteractor: ProductListInteractorInputProtocol {

    weak var presenter: ProductListInteractorOutputProtocol?
    
    func getFavourite(offset: Int) {
        Provider.shared.categoryAPIService.filterRecord(param: RecordParam(), success: { (result) in
            self.presenter?.getSucessFavourite(record: result)
        }) { (error) in
            ProgressView.shared.hide()
        }
       
    }
}
