//
//  OrderDetailViewController.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum OrderDetailInfoType: Int {
    case infoProduct = 0
    case intro
    case infoSaler
    case address
    case comment
}

class OrderDetailViewController: BaseViewController {

	var presenter: OrderDetailPresenterProtocol?
    
    @IBOutlet weak var vPostCommentView: PostCommentView!
    @IBOutlet weak var bottomConstant: NSLayoutConstraint!
    @IBOutlet weak var heightConstant: NSLayoutConstraint!
    
    var record: RecordEntity? {
        didSet {
            tbDetail.reloadData()
        }
    }
    
    var listHeader = ["Chi tiết", "Giới thiệu","Thông tin người bán", "Địa chỉ", "Bình Luận"]
    
    var listComment = [CommentEntity]()
    
    @IBOutlet weak var tbDetail: UITableView!
    
    var tapGesture: UITapGestureRecognizer!

	override func viewDidLoad() {
        super.viewDidLoad()
        addKeyboardNotification()
        vPostCommentView.delegate = self
        configureTable()
        
        presenter?.getDetail(id: "31")
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        setTitleNavigation(title: "Chi tiết sản phẩm")
        addBackToNavigation()
        addButtonToNavigation(image: AppImage.imgShare, style: .right, action: #selector(btnShareTapped))
    }
    
    @objc func btnShareTapped() {
        print("share native")
    }
    
//    func testComment() {
//        for i in 0...3 {
//            let newComment = CommentEntity(comment: "Comment \(i)")
//
//            for j in 0...4 {
//                let newSubComment = SubCommentEntity(comment: "Sub comment \(j)")
//                newComment.subComment.append(newSubComment)
//            }
//
//            listComment.append(newComment)
//        }
//
//        tbDetail.reloadData()
//    }
}

extension OrderDetailViewController: OrderDetailViewProtocol {
    func didGetDetail(record: RecordEntity?) {
        self.record = record
    }
}
