//
//  OrderDetailViewController.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum OrderDetailInfoType: Int {
    case infoProduct = 0
    case intro
    case infoSaler
    case address
    case comment
}

class OrderDetailViewController: BaseViewController, OrderDetailViewProtocol {

	var presenter: OrderDetailPresenterProtocol?
    
    @IBOutlet weak var vPostCommentView: PostCommentView!
    @IBOutlet weak var bottomConstant: NSLayoutConstraint!
    @IBOutlet weak var heightConstant: NSLayoutConstraint!
    
    var listHeader = ["Chi tiết", "Giới thiệu","Thông tin người bán", "Địa chỉ", "Bình Luận"]
    
    var listComment = [CommentEntity]()
    
    @IBOutlet weak var tbDetail: UITableView!
    
    var tapGesture: UITapGestureRecognizer!

	override func viewDidLoad() {
        super.viewDidLoad()
        addKeyboardNotification()
        vPostCommentView.delegate = self
        configureTable()
        
        // FIX ME
        testComment()
    }
    
    func testComment() {
        for i in 0...3 {
            let newComment = CommentEntity(comment: "Comment \(i)")
            
            for j in 0...4 {
                let newSubComment = SubCommentEntity(comment: "Sub comment \(j)")
                newComment.subComment.append(newSubComment)
            }
            
            listComment.append(newComment)
        }
        
        tbDetail.reloadData()
    }
}
