//
//  OrderDetailProtocols.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol OrderDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol OrderDetailPresenterProtocol: class {

    var interactor: OrderDetailInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol OrderDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol OrderDetailInteractorInputProtocol: class {

    var presenter: OrderDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol OrderDetailViewProtocol: class {

    var presenter: OrderDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
