//
//  MySellExpiredViewController.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellExpiredViewController: BaseViewController {

    @IBOutlet weak var lbTotalExpired: UILabel!
    @IBOutlet weak var lbTotalHiden: UILabel!
    @IBOutlet weak var tbExpired: UITableView!
    
	var presenter: MySellExpiredPresenterProtocol?
    var refeshControl: UIRefreshControl?
    
    
    var listSellExpired: [RecordEntity] = [] {
        didSet {
            tbExpired.reloadData()
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        getData()
    }
    
    func setupView() {
        self.setTitleNavigation(title: "Tin hết hạn/ ẩn ")
        addBackToNavigation()
        configTable()
        refeshControl = UIRefreshControl()
        refeshControl?.addTarget(self, action: #selector(self.refeshData), for: .valueChanged)
        tbExpired.addSubview(refeshControl!)
    }
    
    func configTable() {
        tbExpired.delegate = self
        tbExpired.dataSource = self
        
        tbExpired.registerTableCell(MySellingCell.self)
        
        tbExpired.contentInset.bottom = 10
    }
    
    func getData() {
        presenter?.getSellExpired()
    }
    
    @objc private func refeshData() {
        getData()
        refeshControl?.endRefreshing()
    }
    
}

extension MySellExpiredViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(MySellingCell.self)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 130
    }
}

extension MySellExpiredViewController: MySellExpiredViewProtocol {
    func didGetSellPired(data: [RecordEntity]) {
        self.listSellExpired = data
    }
    
    func didGetSellPired(error: APIError?) {
        
    }
}
