//
//  MySellExpiredPresenter.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellExpiredPresenter: MySellExpiredPresenterProtocol {

    weak private var view: MySellExpiredViewProtocol?
    var interactor: MySellExpiredInteractorInputProtocol?
    private let router: MySellExpiredWireframeProtocol

    init(interface: MySellExpiredViewProtocol, interactor: MySellExpiredInteractorInputProtocol?, router: MySellExpiredWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getSellExpired(status: String, limit: Int, offset: Int) {
        interactor?.getSellExpired(status: status, limit: limit, offset: offset)
    }
}

extension MySellExpiredPresenter: MySellExpiredInteractorOutputProtocol {
    func didGetSellPired(data: BaseRecordEntity?) {
        view?.didGetSellPired(data: data)
    }
    
    func didGetSellPired(error: APIError?) {
        view?.didGetSellPired(error: error)
    }
}
