//
//  MySellExpiredViewController.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellExpiredViewController: BaseViewController {

    @IBOutlet weak var lbTotalExpired: UILabel!
    @IBOutlet weak var lbTotalHiden: UILabel!
    @IBOutlet weak var tbExpired: UITableView!
    
	var presenter: MySellExpiredPresenterProtocol?
    var refeshControl: UIRefreshControl?
    
    var listSellExpired: BaseRecordEntity? {
        didSet {
            tbExpired.reloadData()
            
            if (self.listSellExpired?.dataRecord.isEmpty)! {
                tbExpired.isHidden = true
                showNoData()
            } else {
                hideNoData()
            }
            
            lbTotalHiden.text = "Tin đã ẩn: \(listSellExpired?.countHide ?? 0)"
            lbTotalExpired.text = "Tin hết hạn: \(listSellExpired?.countExpired ?? 00)"
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        getData()
    }
    
    func setupView() {
        self.setTitleNavigation(title: "Tin hết hạn/ ẩn ")
        addBackToNavigation()
        self.tabBarController?.tabBar.isHidden = true
        configTable()
        refeshControl = UIRefreshControl()
        refeshControl?.addTarget(self, action: #selector(self.refeshData), for: .valueChanged)
        tbExpired.addSubview(refeshControl!)
        
    }
    
    func configTable() {
        tbExpired.delegate = self
        tbExpired.dataSource = self
        
        tbExpired.registerTableCell(MySellingCell.self)
        
        tbExpired.contentInset.bottom = 10
//        tbExpired.separatorStyle = .none
        tbExpired.tableFooterView = UIView()
    }
    
    func getData() {
        presenter?.getSellExpired(status: "hide", limit: 10, offset: 0)
    }
    
    @objc private func refeshData() {
        getData()
        refeshControl?.endRefreshing()
    }
    
}

extension MySellExpiredViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let count = listSellExpired?.dataRecord.count else { return 0}
        return count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(MySellingCell.self)
        cell.vRecordSelling.record = listSellExpired?.dataRecord[indexPath.item]
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 130
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let record = listSellExpired?.dataRecord[indexPath.item]
        let vc = OrderDetailRouter.createModule(recordId: record?.id)
        if record?.status == "hide" {
            vc.isMySellHide = true
        } else if listSellExpired?.dataRecord[indexPath.item].status == "expired" {
            vc.isMySellExpired = true
        }
        
        self.navigationController?.pushViewController(vc, animated: true)
    }
}

extension MySellExpiredViewController: MySellExpiredViewProtocol {
    
    func didGetSellPired(data: BaseRecordEntity?) {
        self.listSellExpired = data
    }
    
    func didGetSellPired(error: APIError?) {
        
    }
}
