//
//  PostStepOneProtocols.swift
//  Oganban
//
//  Created Kai Pham on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PostStepOneWireframeProtocol: class {

}
//MARK: Presenter -
protocol PostStepOnePresenterProtocol: class {

    var interactor: PostStepOneInteractorInputProtocol? { get set }
    func getCategoryMerge()
    func getExpireDate()
}

//MARK: Interactor -
protocol PostStepOneInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetCategoryMerge(list: [CategoryMergeEntity])
}

protocol PostStepOneInteractorInputProtocol: class {

    var presenter: PostStepOneInteractorOutputProtocol?  { get set }
    func getCategoryMerge()
    func getExpireDate()
    /* Presenter -> Interactor */
}

//MARK: View -
protocol PostStepOneViewProtocol: class {

    var presenter: PostStepOnePresenterProtocol?  { get set }
    func didGetCategoryMerge(list: [CategoryMergeEntity])

    /* Presenter -> ViewController */
}
