//
//  PostStepOneInteractor.swift
//  Oganban
//
//  Created Kai Pham on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PostStepOneInteractor: PostStepOneInteractorInputProtocol {

    weak var presenter: PostStepOneInteractorOutputProtocol?
    
    func getCategoryMerge() {
        Provider.shared.categoryAPIService.getCategoryMerge(success: { (result) in
            self.presenter?.didGetCategoryMerge(list: result)
        }) { (error) in
            print("PostStepOneInteractor: \(String(describing: error?.message&))")
        }
    }
    
    func getExpireDate() {
        ProgressView.shared.show()
        Provider.shared.recordAPIService.getExpireDateRecord(success: { expireEntity in
            guard let date = expireEntity?.expiredDate else { return }
            DataManager.shared.maxDate = date
            ProgressView.shared.hide()
        }) { error in
            ProgressView.shared.hide()
            print("PostStepOneInteractor: \(String(describing: error?.message&))")
        }
    }
}
