//
//  PostStepOneRouter.swift
//  Oganban
//
//  Created Kai Pham on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PostStepOneRouter: PostStepOneWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PostStepOneViewController(nibName: nil, bundle: nil)
        let interactor = PostStepOneInteractor()
        let router = PostStepOneRouter()
        let presenter = PostStepOnePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    static func createModule(record: RecordEntity?) -> PostStepOneViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PostStepOneViewController(nibName: nil, bundle: nil)
        let interactor = PostStepOneInteractor()
        let router = PostStepOneRouter()
        let presenter = PostStepOnePresenter(interface: view, interactor: interactor, router: router)
        
        view.record = record
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
