//
//  MySellContainerViewController.swift
//  Oganban
//
//  Created Kai Pham on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellContainerViewController: UIViewController, MySellContainerViewProtocol {

	var presenter: MySellContainerPresenterProtocol?
    @IBOutlet weak var vPageView: AppPageView!
    
    var listControllers = [UIViewController]()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let vc1 = UIViewController()
//        vc1.view.backgroundColor = .red
        
        let vc2 = UIViewController()
//        vc2.view.backgroundColor = .green
        
        let listItem = [
            KCategory(title: "ĐANG BÁN", isSelected: true),
            KCategory(title: "GIAO DỊCH", isSelected: false)
        ]
        
        self.listControllers = [vc1, vc2]
        vPageView.setUpMenuAndController(controllers: listControllers, menuColorBackground: AppColor.white, menuFont: AppFont.fontRegular11, menuColorNormal: AppColor.gray_158_158_158, menuColorSelected: AppColor.green, menuColorHorizontal: AppColor.red_110_0_0, heightHorizontal: 2, listItem: listItem, isFull: true, isHaveLineTop: false)
    }

}
