//
//  MySellContainerProtocols.swift
//  Oganban
//
//  Created Kai Pham on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MySellContainerWireframeProtocol: class {

    func gotoLogin()
}
//MARK: Presenter -
protocol MySellContainerPresenterProtocol: class {

    var interactor: MySellContainerInteractorInputProtocol? { get set }
    func gotoLogin()
}

//MARK: Interactor -
protocol MySellContainerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MySellContainerInteractorInputProtocol: class {

    var presenter: MySellContainerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MySellContainerViewProtocol: class {

    var presenter: MySellContainerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
