//
//  MySellContainerRouter.swift
//  Oganban
//
//  Created Kai Pham on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellContainerRouter: MySellContainerWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MySellContainerViewController(nibName: nil, bundle: nil)
        let interactor = MySellContainerInteractor()
        let router = MySellContainerRouter()
        let presenter = MySellContainerPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoLogin() {
        let vc = LoginRouter.createModule()
        let nc = UINavigationController(rootViewController: vc)
        viewController?.present(controller: nc, animated: true)
    }
    
    func gotoMySellExpired() {
        let mySellExpiredVC = MySellExpiredRouter.createModule()
        viewController?.push(controller: mySellExpiredVC)
    }
}
