//
//  HistoryCoinInteractor.swift
//  Oganban
//
//  Created Kent on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryCoinInteractor: HistoryCoinInteractorInputProtocol {
    
    weak var presenter: HistoryCoinInteractorOutputProtocol?
    
    func getHistoryCoin(offset: Int) {
        
        ProgressView.shared.show()
        Provider.shared.orderAPIService.getHistoryCoin(offset: offset, success: { (historyCoin) in
            ProgressView.shared.hide()
            self.presenter?.getSucessHistoryCoin(history: historyCoin)
        }) { (error) in
            ProgressView.shared.hide()
            self.presenter?.getErrorHistoryCoin(error: error)
        }
    }
}
