//
//  HistoryCoinProtocols.swift
//  Oganban
//
//  Created Kent on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryCoinWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryCoinPresenterProtocol: class {

    var interactor: HistoryCoinInteractorInputProtocol? { get set }
    func getHistoryCoin(offset: Int)
}

//MARK: Interactor -
protocol HistoryCoinInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getSucessHistoryCoin(history: BaseHistoryCoinEntity?)
    func getErrorHistoryCoin(error: APIError?)
}

protocol HistoryCoinInteractorInputProtocol: class {

    var presenter: HistoryCoinInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getHistoryCoin(offset: Int)
}

//MARK: View -
protocol HistoryCoinViewProtocol: class {

    var presenter: HistoryCoinPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getSucessHistoryCoin(history: BaseHistoryCoinEntity?)
    func getErrorHistoryCoin(error: APIError?)
}
