//
//  HomeInteractor.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/18/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {
    func filterRecord(param: RecordParam) {
        ProgressView.shared.show()
        Provider.shared.categoryAPIService.filterRecord(param: param, success: { (result) in
            ProgressView.shared.hide()
            self.presenter?.didFilterRecord(list: result)
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
    
    func getCategoryMerge() {
        Provider.shared.categoryAPIService.getCategoryMerge(success: { (result) in
            self.presenter?.didGetCategoryMerge(list: result)
        }) { (error) in
            
        }
    }
    
    func getCategoryChild(id: String) {
        Provider.shared.categoryAPIService.getCategoryChild(categoryId: id, success: { (result) in
            self.presenter?.getCategoryChildSuccess(list: result)
        }) { (error) in
            
        }
    }
    
    func getCategory() {
        Provider.shared.categoryAPIService.getCategory(success: { (result) in
            self.presenter?.getCategorySuccess(list: result)
        }) { (error) in
            
        }
    }
    

    weak var presenter: HomeInteractorOutputProtocol?
}
