//
//  MybuyInteractor.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MybuyInteractor: MybuyInteractorInputProtocol {

    weak var presenter: MybuyInteractorOutputProtocol?
}
