//
//  MyBuyPresenter.swift
//  Oganban
//
//  Created Coby on 12/29/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyBuyPresenter: MyBuyPresenterProtocol, MyBuyInteractorOutputProtocol {

    weak private var view: MyBuyViewProtocol?
    var interactor: MyBuyInteractorInputProtocol?
    private let router: MyBuyWireframeProtocol

    init(interface: MyBuyViewProtocol, interactor: MyBuyInteractorInputProtocol?, router: MyBuyWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
