//
//  MyBuyInteractor.swift
//  Oganban
//
//  Created Coby on 12/18/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyBuyInteractor: MyBuyInteractorInputProtocol {

    weak var presenter: MyBuyInteractorOutputProtocol?
}
