//
//  MybuyViewController.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MybuyViewController: UIViewController, MybuyViewProtocol {

	var presenter: MybuyPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .yellow
    }

}
