//
//  MybuyProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MybuyWireframeProtocol: class {

}
//MARK: Presenter -
protocol MybuyPresenterProtocol: class {

    var interactor: MybuyInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MybuyInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MybuyInteractorInputProtocol: class {

    var presenter: MybuyInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MybuyViewProtocol: class {

    var presenter: MybuyPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
