//
//  MorePresenter.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MorePresenter: MorePresenterProtocol, MoreInteractorOutputProtocol {

    weak private var view: MoreViewProtocol?
    var interactor: MoreInteractorInputProtocol?
    private let router: MoreWireframeProtocol

    init(interface: MoreViewProtocol, interactor: MoreInteractorInputProtocol?, router: MoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
