//
//  MoreInteractor.swift
//  Oganban
//
//  Created Admin on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreInteractor: MoreInteractorInputProtocol {

    weak var presenter: MoreInteractorOutputProtocol?
}
