//
//  MoreRouter.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreRouter: MoreWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MoreViewController(nibName: nil, bundle: nil)
        let interactor = MoreInteractor()
        let router = MoreRouter()
        let presenter = MorePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToPage (name: MoreEntityType){
        switch name {
        case MoreEntityType.header:
            tapHeader()
            print("Tap header")
            break
        case MoreEntityType.historyCoin:
            tapHistoryCoin()
            print("Chọn Lịch sử ƠCoin")
            break
        case MoreEntityType.historyBuy:
            tapHistoryBuy()
            print("Chọn Lịch sử mua tin")
            break
        case MoreEntityType.policy:
            tapPolicy()
            print("Chọn Điều khoản sử dụng")
            break
        case MoreEntityType.tutorial:
            print("Chọn Hướng dẫn")
            break
        case MoreEntityType.setting:
            print("Chọn Cài đặt")
            break
        case MoreEntityType.changePassword:
            tapChangePassword()
            print("Chọn Đổi mật khẩu")
            break
        case MoreEntityType.logout:
            print("Chọn Đăng xuất")
            
            break
        default:
            break
        }
        
    }
    
    private func tapHeader(){
        if UserDefaultHelper.shared.loginUserInfo != nil {
            let vc = UpdateProfileRouter.createModule()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        } else {
            let vc = LoginRouter.createModule()
            viewController?.present(controller: vc, animated: true)
        }
    }
    
    private func tapHistoryCoin(){
        if UserDefaultHelper.shared.loginUserInfo != nil {
            //Goto histotyCoin
        } else {
            let vc = LoginRouter.createModule()
            viewController?.present(controller: vc, animated: true)
        }
    }
    
    private func tapHistoryBuy(){

    }
    
    private func tapPolicy(){
    }
    
    private func tapChangePassword() {
        let vc = ChangePasswordRouter.createModule()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
