//
//  MoreRouter.swift
//  Oganban
//
//  Created Kent on 12/20/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreRouter: MoreWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MoreViewController(nibName: nil, bundle: nil)
        let interactor = MoreInteractor()
        let router = MoreRouter()
        let presenter = MorePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goToPage (name: MoreRowName){
        switch name {
        case MoreRowName.header:
            tapHeader()
            print("Tap header")
            break
        case MoreRowName.historyCoin:
            tapHistoryCoin()
            print("Chọn Lịch sử ƠCoin")
            break
        case MoreRowName.historyBuy:
            tapHistoryBuy()
            print("Chọn Lịch sử mua tin")
            break
        case MoreRowName.policy:
            tapPolicy()
            print("Chọn Điều khoản sử dụng")
            break
        case MoreRowName.tutorial:
            print("Chọn Hướng dẫn")
            break
        case MoreRowName.setting:
            print("Chọn Cài đặt")
            break
        case MoreRowName.changePassword:
            print("Chọn Đổi mật khẩu")
            break
        case MoreRowName.logout:
            print("Chọn Đăng xuất")
            break
        default:
            break
        }
        
    }
    
    private func tapHeader(){
        if UserDefaultHelper.shared.loginUserInfo != nil {
            let vc = UpdateProfileRouter.createModule()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        } else {
            let vc = LoginRouter.createModule()
            viewController?.present(controller: vc, animated: true)
        }
    }
    
    private func tapHistoryCoin(){
        let vc = LoginRouter.createModule()
        viewController?.present(controller: vc, animated: true)
    }
    
    private func tapHistoryBuy(){

    }
    
    private func tapPolicy(){
    }
    
}
