//
//  PostStepOneViewController.swift
//  Oganban
//
//  Created Kai Pham on 1/4/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PostStepOneViewController: BaseViewController, PostStepOneViewProtocol {
    
    var presenter: PostStepOnePresenterProtocol?
    @IBOutlet weak var vTitleRecord       : FTextField!
    @IBOutlet weak var vQuantity       : FTextField!
    @IBOutlet weak var vChooseDate       : FTextFieldChoose!
    @IBOutlet weak var vAbout       : AppTextView!
    @IBOutlet weak var lbCategory       : UILabel!
    @IBOutlet weak var vPhoto       : AppCollectionPhoto!
    @IBOutlet weak var heightPhoto       : NSLayoutConstraint!
    
    var postParam = PostRecordParam()
    var category: CategoryEntity?
    var dateSeleted: Date?
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
        setTitleNavigation(title: "Đăng tin bán")
        setRedStatusBar()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        hideTabbar()
    }
    
    override func setUpViews() {
        super.setUpViews()
        vTitleRecord.setTextField(title: TitleString.titleRecord, placeHolder: TitleString.placeTitleRecord)
        
        vQuantity.setTextField(title: TitleString.titleQuantity, placeHolder: TitleString.placeTitleQuantity)
        
        vChooseDate.setTextField(title: TitleString.titleExpireSell, placeHolder: TitleString.placeTitleExpireSell)
        
        vAbout.setTitlePlaceHolder(title: "Giới thiệu *", placeHolder: "Nhập giới thiệu sản phẩm (Tối đa 1,500 ký tự)")
        
        //
        vPhoto.configCollectionImageView(delegate: self, controller: self, isSingleSelected: false)
        vChooseDate.delegate = self
        
        //--
        vQuantity.textField.keyboardType = UIKeyboardType.numberPad
    }
    
    @IBAction func btnCategoryTapped() {
        print("show category")
    }
    
    @IBAction func btnContinueTapped() {
        let imgSrc = vPhoto.listImage.map {$0.url&}
        let expireDate = dateSeleted?.toString(dateFormat: AppDateFormat.yyyyMMdd)&
        
        postParam = PostRecordParam(categoryId: "128", name: vTitleRecord.textField.text&, imgSrc: imgSrc, quantity: vQuantity.textField.text&, expireDate: expireDate&, aboutRecord: vAbout.tvInput.text&)
        
        let vc = PostStepTwoRouter.createModule(param: self.postParam)
        self.push(controller: vc)
    }
    
}

extension PostStepOneViewController: AppCollectionPhotoDelegate {
    func appCollectionPhoto(_ collectionView: AppCollectionPhoto, changedHeight height: CGFloat) {
        heightPhoto.constant = height
    }
    
    func appCollectionPhoto(_ collectionView: AppCollectionPhoto, selectedImages images: [AppPhoto]) {
        
    }
}

extension PostStepOneViewController: FTextFieldChooseDelegate {
    func btnChooseTapped(sender: FTextFieldChoose) {
        PopUpHelper.shared.showDateFollowWeekPopup { date in
            self.dateSeleted = date
            self.vChooseDate.textField.text = date?.toString(dateFormat: AppDateFormat.ddMMYYYY_VN)
        }
    }
}
