//
//  HistoryBuyViewController.swift
//  Oganban
//
//  Created Admin on 1/5/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryBuyViewController: BaseViewController, HistoryBuyViewProtocol {

    @IBOutlet weak var tvHistory: UITableView!
    var historyList = ["1","2","3","4","5"]

    var presenter: HistoryBuyPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.addBackToNavigation(icon: AppImage.imgWhiteBack)
        self.setTitleNavigation(title: NavigationTitle.historyBuy)
        registerTableView()
    }
    
    func registerTableView() {
        tvHistory.dataSource = self
        tvHistory.delegate = self
        tvHistory.registerXibFile(HistoryBuyCell.self)
        tvHistory.tableFooterView = UIView()
        tvHistory.estimatedRowHeight = 100
        tvHistory.translatesAutoresizingMaskIntoConstraints = false
        tvHistory.rowHeight = UITableView.automaticDimension
    }
}
extension HistoryBuyViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return historyList.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(HistoryBuyCell.self, for: indexPath) as HistoryBuyCell
        cell.showData(index: indexPath.row)
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return  UITableView.automaticDimension
    }
}
