//
//  CommentDetailProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 1/12/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CommentDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol CommentDetailPresenterProtocol: class {

    var interactor: CommentDetailInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol CommentDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol CommentDetailInteractorInputProtocol: class {

    var presenter: CommentDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol CommentDetailViewProtocol: class {

    var presenter: CommentDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
