//
//  CommentDetailInteractor.swift
//  Oganban
//
//  Created DINH VAN TIEN on 1/12/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CommentDetailInteractor: CommentDetailInteractorInputProtocol {

    weak var presenter: CommentDetailInteractorOutputProtocol?
}
