//
//  CommentDetailProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 1/12/19.
//  Copyright © 2019 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CommentDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol CommentDetailPresenterProtocol: class {

    var interactor: CommentDetailInteractorInputProtocol? { get set }
    
    func sendComment(param: SendCommentParam)
    func sendSubComment(param: SendCommentParam)
    func getCommentList(recordId: String, offset: Int)
}

//MARK: Interactor -
protocol CommentDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didSendComment(comment: CommentEntity?)
    func didSubSendComment(comment: SubCommentEntity?)
    func didGetComment(commentResponseEntity: CommentResponseEntity?)
    
}

protocol CommentDetailInteractorInputProtocol: class {

    var presenter: CommentDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func sendComment(param: SendCommentParam)
    func getCommentList(recordId: String, offset: Int)
}

//MARK: View -
protocol CommentDetailViewProtocol: class {

    var presenter: CommentDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didSendComment(comment: CommentEntity?)
    func didSendSubComment(comment: SubCommentEntity?)
    func didGetComment(commentResponseEntity: CommentResponseEntity?)
}
