//
//  UpdateProfileViewController.swift
//  Oganban
//
//  Created Admin on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UpdateProfileViewController: BaseViewController, UpdateProfileViewProtocol {

	var presenter: UpdateProfilePresenterProtocol?
    
    @IBOutlet weak var lbError: UILabel!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var tfPhoneCode: OganbanCustomTextfield!
    @IBOutlet weak var imgAvatar: UIImageView!
    @IBOutlet weak var btnSave: OganbanCustomButton!
    @IBOutlet weak var tfAddress2: OganbanCustomTextfield!
    @IBOutlet weak var tfAddress1: OganbanCustomTextfield!
    @IBOutlet weak var tfPhone: OganbanCustomTextfield!
    @IBOutlet weak var tfGender: OganbanCustomTextfield!
    @IBOutlet weak var tfBirthday: OganbanCustomTextfield!
    @IBOutlet weak var tfDisplayName: OganbanCustomTextfield!
    @IBOutlet weak var tfUsername: OganbanCustomTextfield!
    
    var birthDay: Date? = nil
    var gender: Gender? = nil
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        tapSaveButton()
        textFieldDidBeginEditing()
    }

    func setupView(){
        self.setTitleNavigation(title: "Thông tin tài khoản")
        self.addBackToNavigation()
        
        hideError()
        
        imgAvatar.layer.cornerRadius = imgAvatar.frame.width / 2.0
        imgAvatar.layer.masksToBounds = true
        
        tfUsername.setupLayoutTextfield(placeholderText: "example@gmail.com", titleText: "Tên đăng nhập *", placeholderColor: AppColor.black414141)
        
        tfDisplayName.setupLayoutTextfield(placeholderText: "Nhập tên hiển thị", titleText: "Tên hiển thị *", placeholderColor: AppColor.black414141)
        
        tfBirthday.setupLayoutTextfield(placeholderText: "Chọn ngày", titleText: "Ngày tháng năm sinh *", placeholderColor: AppColor.black414141)
        tfBirthday.showRightIcon(sỉze: CGSize(width: 11, height: 11), icon: AppImage.imgArrowDown)
        tfBirthday.tfContent.isEnabled = false
        let tapBirthdayGesture = UITapGestureRecognizer(target: self, action: #selector(self.selectBirthday(_:)))
        self.tfBirthday.addGestureRecognizer(tapBirthdayGesture)
        
        tfGender.setupLayoutTextfield(placeholderText: "Chọn giới tính", titleText: "Giới tính", placeholderColor: AppColor.black414141)
        tfGender.showRightIcon(sỉze: CGSize(width: 11, height: 11), icon: AppImage.imgArrowDown)
        tfGender.tfContent.isEnabled = false
        let tapSexGesture = UITapGestureRecognizer(target: self, action: #selector(self.selectSex(_:)))
        self.tfGender.addGestureRecognizer(tapSexGesture)
        
        tfPhoneCode.setupLayoutTextfield(placeholderText: "+84", titleText: "", placeholderColor: AppColor.black414141)
        tfPhoneCode.showRightIcon(sỉze: CGSize(width: 11, height: 11), icon: AppImage.imgArrowDown, paddingRight: -12)
        tfPhoneCode.tfContent.isEnabled = false
        tfPhone.setupLayoutTextfield(placeholderText: "Nhập số điện thoại của bạn", titleText: "", placeholderColor: AppColor.black414141)
        tfPhone.tfContent.keyboardType = .numberPad
        
        tfAddress1.setupLayoutTextfield(placeholderText: "Bạn có thể nhập địa chỉ nhà", titleText: "Địa chỉ 1", placeholderColor: AppColor.black414141)
        tfAddress2.setupLayoutTextfield(placeholderText: "Bạn có thể nhập địa chỉ công ty", titleText: "Địa chỉ 2", placeholderColor: AppColor.black414141)
        
        btnSave.setupLayoutButton(backgroundColor: AppColor.green005800, titleColor: AppColor.white, text: "Lưu thay đổi")
        scrollView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        
    }
    
    func validateInputData() -> Bool {
        
        guard let username = self.tfUsername.tfContent.text else {
            hideError(isHidden: false, message: "Vui lòng nhập tên đăng nhập")
            return false
        }
        
        if username == ""  {
            hideError(isHidden: false, message: "Vui lòng nhập tên đăng nhập")
            return false
        }
        
        if username.isValidEmail() == false  {
            hideError(isHidden: false, message: "Vui lòng kiểm tra lại tên đăng nhập")
            return false
        }
        
        guard let displayName = self.tfDisplayName.tfContent.text else {
            hideError(isHidden: false, message: "Vui lòng nhập tên hiển thị")
            return false
        }
        
        if displayName == "" {
            hideError(isHidden: false, message: "Vui lòng nhập tên hiển thị")
            return false
        }
        
        guard let birthDay =  self.birthDay else {
            hideError(isHidden: false, message: "Vui lòng chọn ngày tháng năm sinh")
            return false
        }
        
        let age = calculateAge(birthday: birthDay)
        if age < 15  {
            hideError(isHidden: false, message: "Vui lòng kiểm tra lại tuổi phải trên 15")
            return false
        }
        
        guard let phone =  self.tfPhone.tfContent.text else {
            hideError(isHidden: false, message: "Vui lòng nhập số điện thoại")
            return false
        }
        
        if phone == "" {
            hideError(isHidden: false, message: "Vui lòng nhập số điện thoại")
            return false
        }
        
        if phone.isValidPhone2() == false {
            hideError(isHidden: false, message: "Vui lòng kiểm tra lại số điện thoại")
            return false
        }
        
        hideError()
        return true
    }
    
    @IBAction func tapShareButton(_ sender: UIButton) {
        print("TAP SHARE BUTTON")
    }
    
}

extension UpdateProfileViewController {
    func hideError(isHidden: Bool = true, message: String? = nil){
        lbError.isHidden = isHidden
        lbError.text = message ?? ""
    }
    
    func textFieldDidBeginEditing() {
        tfUsername.textFieldDidBeginEditing = {
            self.hideError()
        }
        tfDisplayName.textFieldDidBeginEditing = {
            self.hideError()
        }
        tfPhone.textFieldDidBeginEditing = {
            self.hideError()
        }
        tfAddress1.textFieldDidBeginEditing = {
            self.hideError()
        }
        tfAddress2.textFieldDidBeginEditing = {
            self.hideError()
        }
    }
    
    func tapSaveButton(){
        btnSave.tapButton = {
            self.view.endEditing(true)
            if self.validateInputData() {
                print("Update Success")
            } else {
                print("Update Error")
            }
        }
    }
    
    @objc func selectBirthday(_ sender: UITapGestureRecognizer) {
        hideError()
        let popUp = PopUpSelectDate()
        popUp.vDateContent.vPickerDate.maximumDate = Date()
        popUp.showPopUp(currentDate: birthDay) { (date) in
            if let date = date {
                self.birthDay = date
                self.tfBirthday.tfContent.text =  date.toString(dateFormat: AppDateFormat.ddMMYYYY_VN)
            }
        }
    }
    
    @objc func selectSex(_ sender: UITapGestureRecognizer) {
        hideError()
        let popUp = PopUpSelectGender()
        popUp.showPopUp(currentGender: self.gender ) { (gender) in
            if let sex: Gender = gender as? Gender {
                self.gender = sex
                self.tfGender.tfContent.text = sex.title
            }
        }
    }
    
    func calculateAge(birthday: Date) -> Int {
        let now = Date()
        let calendar = Calendar.current
        let ageComponents = calendar.dateComponents([.year], from: birthday, to: now)
        return ageComponents.year!
    }
}
