//
//  UpdateProfileProtocols.swift
//  Oganban
//
//  Created Admin on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UpdateProfileWireframeProtocol: class {

}
//MARK: Presenter -
protocol UpdateProfilePresenterProtocol: class {

    var interactor: UpdateProfileInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol UpdateProfileInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol UpdateProfileInteractorInputProtocol: class {

    var presenter: UpdateProfileInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol UpdateProfileViewProtocol: class {

    var presenter: UpdateProfilePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
