//
//  UpdateProfileProtocols.swift
//  Oganban
//
//  Created Kent on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UpdateProfileWireframeProtocol: class {

}
//MARK: Presenter -
protocol UpdateProfilePresenterProtocol: class {

    var interactor: UpdateProfileInteractorInputProtocol? { get set }
    func updateProfile(userInfo: UserEntity)
}

//MARK: Interactor -
protocol UpdateProfileInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didSuccessUpdateProfile(user: UserEntity?)
    func didErrorUpdateProfile(error: APIError?)
}

protocol UpdateProfileInteractorInputProtocol: class {

    var presenter: UpdateProfileInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    
    func updateProfile(userInfo: UserEntity)
}

//MARK: View -
protocol UpdateProfileViewProtocol: class {

    var presenter: UpdateProfilePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didSuccessUpdateProfile(user: UserEntity?)
    func didErrorUpdateProfile(error: APIError?)
}
