//
//  UpdateProfilePresenter.swift
//  Oganban
//
//  Created Kent on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UpdateProfilePresenter: UpdateProfilePresenterProtocol, UpdateProfileInteractorOutputProtocol {

    weak private var view: UpdateProfileViewProtocol?
    var interactor: UpdateProfileInteractorInputProtocol?
    private let router: UpdateProfileWireframeProtocol

    init(interface: UpdateProfileViewProtocol, interactor: UpdateProfileInteractorInputProtocol?, router: UpdateProfileWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
