//
//  UpdateProfileInteractor.swift
//  Oganban
//
//  Created Admin on 12/22/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UpdateProfileInteractor: UpdateProfileInteractorInputProtocol {

    weak var presenter: UpdateProfileInteractorOutputProtocol?
}
