//
//  SignUpPresenter.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/18/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPresenter: SignUpPresenterProtocol {

    weak private var view: SignUpViewProtocol?
    var interactor: SignUpInteractorInputProtocol?
    private let router: SignUpWireframeProtocol

    init(interface: SignUpViewProtocol, interactor: SignUpInteractorInputProtocol?, router: SignUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getCaptcha() {
        interactor?.getCaptcha()
    }
    
    func signUp(param: SignUpParam) {
        interactor?.signUp(param: param)
    }
}

extension SignUpPresenter: SignUpInteractorOutputProtocol {
    func successCaptcha(image: UIImage) {
        view?.successCaptcha(image: image)
    }
    
    func signUpSuccess(user: UserEntity?) {
        view?.signUpSuccess(user: user)
    }
    
    func signUpError(error: APIError) {
        view?.signUpError(error: error)
    }
}
