//
//  SignUpProtocols.swift
//  Oganban
//
//  Created DINH VAN TIEN on 12/18/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPresenterProtocol: class {

    var interactor: SignUpInteractorInputProtocol? { get set }
    func getCaptcha()
    func signUp(param: SignUpParam)
    func verifyPhone(verifyCode: String, phoneCode: String, phoneNum: String)
}

//MARK: Interactor -
protocol SignUpInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func successCaptcha(image: UIImage)
    func signUpSuccess(user: UserEntity?)
    func signUpError(error: APIError)
    func didVerifyPhone(response: BaseResponse?)
    func didVerifyPhone(error: APIError?)
}

protocol SignUpInteractorInputProtocol: class {

    var presenter: SignUpInteractorOutputProtocol?  { get set }
    func getCaptcha()
    func signUp(param: SignUpParam)
    func verifyPhone(verifyCode: String, phoneCode: String, phoneNum: String)
    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignUpViewProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func successCaptcha(image: UIImage)
    func signUpSuccess(user: UserEntity?)
    func signUpError(error: APIError)
    func didVerifyPhone(response: BaseResponse?)
    func didVerifyPhone(error: APIError?)
}
