//
//  OrderDetailProtocols.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MySellExpiredDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol MySellExpiredDetailPresenterProtocol: class {

    var interactor: MySellExpiredDetailInteractorInputProtocol? { get set }
    
    func getDetail(id: String)
    func deleteRecord(recordID: String)
}

//MARK: Interactor -
protocol MySellExpiredDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetDetail(record: RecordEntity?)
    func didDeleteRecord(data: BaseResponse?)
}

protocol MySellExpiredDetailInteractorInputProtocol: class {

    var presenter: MySellExpiredDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getDetail(id: String)
    func deleteRecord(recordID: String)
}

//MARK: View -
protocol MySellExpiredDetailViewProtocol: class {

    var presenter: MySellExpiredDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetDetail(record: RecordEntity?)
    func didDeleteRecord(data: BaseResponse?)
}
