//
//  OrderDetailInteractor.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MySellExpiredDetailInteractor: MySellExpiredDetailInteractorInputProtocol {

    weak var presenter: MySellExpiredDetailInteractorOutputProtocol?
    
    func getDetail(id: String) {
        ProgressView.shared.show()
        Provider.shared.recordAPIService.getRecordDetail(id: id, success: { record in
            ProgressView.shared.hide()
            self.presenter?.didGetDetail(record: record)
        }) { _ in
            ProgressView.shared.hide()
        }
    }
    
    func deleteRecord(recordID: String) {
        Provider.shared.recordAPIService.deleteRecord(recordID: recordID, success: { (data) in
            self.presenter?.didDeleteRecord(data: data)
        }) { (_) in
            ProgressView.shared.hide()
        }
    }
    
    func getExpiredDay() {
        ProgressView.shared.show()
        Provider.shared.recordAPIService.getExpireDateRecord(success: { expireEntity in
            guard let date = expireEntity?.expiredDate else { return }
            DataManager.shared.maxDate = date
            ProgressView.shared.hide()
        }) { error in
            ProgressView.shared.hide()
            
        }
    }
    
    func editRecord(recordID: String, expiredDate: String) {
        ProgressView.shared.show()
        Provider.shared.recordAPIService.updateRecord(recordID: recordID, expiredDate: expiredDate, success: { (data) in
            self.presenter?.didEditRecord(data: data)
            ProgressView.shared.hide()
        }) { (_) in
            ProgressView.shared.hide()
        }
    }
}
