//
//  OrderDetailRouter.swift
//  Oganban
//
//  Created Kai Pham on 12/23/18.
//  Copyright © 2018 Coby. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OrderBuyDetailRouter: OrderBuyDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(recordId: String?) -> OrderBuyDetailViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = OrderBuyDetailViewController(nibName: nil, bundle: nil)
        let interactor = OrderBuyDetailInteractor()
        let router = OrderBuyDetailRouter()
        let presenter = OrderBuyDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.recordId = recordId
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
